# Generated by Django 4.0.1 on 2022-02-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestblood',
            name='units',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
