# Generated by Django 4.0.2 on 2022-02-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_requestblood_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='image',
            field=models.ImageField(upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
