# Generated by Django 4.0.2 on 2022-02-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_donor_image_alter_donor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='units_blood_donated',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
