# Generated by Django 4.0.2 on 2022-03-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_donor_units_blood_donated'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestblood',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=500),
        ),
    ]
