# Generated by Django 4.0.2 on 2022-03-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_requestblood_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=500)),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.requestblood')),
            ],
        ),
    ]
