# Generated by Django 4.0.2 on 2022-03-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
