# Generated by Django 4.0.2 on 2022-03-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_donation_history_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_history',
            name='donation_date',
            field=models.DateField(blank=True),
        ),
    ]
